version: '3.1'

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: cncounter
      MYSQL_DATABASE: cncounter
    volumes:
      - ./tools/docker/mysql/init:/docker-entrypoint-initdb.d
      - ~/tmp/docker_data/cncounter/mysql:/var/lib/mysql

  redis:
    image: redis:4.0.11
    ports:
      - 26379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

